# This is the GPU version, if you do not have a GPU, you probably want to install the CPU environment!
name: arcface
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # onnxruntime requires python3.9 and nothing higher.
  - python=3.9
  - pip
  - cpuonly
  - pytorch-cuda
  - torchvision
  - torchaudio
  - onnx  # For ArcFace
  - pip:
    - facenet_pytorch
    - ipywidgets
    - jupyterlab
    - matplotlib
    - notebook
    - onnxruntime-gpu
    - pandas
    - pillow
    - scipy=1.9.3  # Because there is a problem with building 1.10 on Mac OSX Mojave (Zirk's computer)
    - scikit-image
    - tqdm
