# Partially copied from the Deep Learning course environment.
name: fact-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Some packages cannot handle python 3.11 yet, unfortunately
  - python=3.10.8
  - pip=22.3.1
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pip:
    # Additional ML pipeline packages
    - pytorch-lightning~=1.8.3
    - tensorboard~=2.10.1
    # lovely-tensors?
    # mate?
    # Mathematical/plotting packages
    - numpy~=1.24.0
    - pandas~=1.5.2
    - scipy~=1.9.3
    - scikit-learn~=1.2.0
    - matplotlib~=3.6.2
    - seaborn~=0.12.2
    - pillow~=9.4.0
    # Utility packages
    - notebook~=6.5.2
    - ipywidgets~=8.0.0
    - jupyterlab~=3.5.2
    # papermill?  # For running notebooks with parameters and from a script.
    - tqdm>=4.64.1,<5
    - tabulate~=0.9.0
    - typing_extensions~=4.4.0
